In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading dataset using pandas

In [3]:
data=pd.read_csv('DSDataLastThreeMonths.csv')

In [4]:
data.head(10)

CASTNO  HM_WT  AIM_S   HM_S   HM_C  HM_SI  HM_TI  HM_MN  CAC2  MG  HM_TEMP  \
0  V99790    171  0.005  0.040  4.572  0.518  0.069  0.040   347  49   1387.0   
1  V99791    161  0.005  0.035  4.580  0.559  0.070  0.041   361  45   1386.0   
2  V99789    170  0.005  0.042  4.590  0.468  0.044  0.036   355  52   1368.0   
3  V99787    159  0.005  0.034  4.530  0.737  0.077  0.040   313  44   1401.0   
4  V99782    162  0.005  0.042  4.560  0.443  0.056  0.037   360  55   1346.0   
5  V99781    165  0.005  0.035  4.520  0.480  0.056  0.037   323  49   1407.0   
6  V99779    167  0.005  0.040  4.560  0.630  0.069  0.037   349  51   1395.0   
7  V99778    163  0.005  0.040  4.560  0.547  0.057  0.036   346  78   1373.0   
8  V99777    164  0.005  0.050  4.500  0.397  0.049  0.037   373  72   1386.0   
9  V99776    162  0.005  0.039  4.520  0.622  0.069  0.040   344  56   1357.0   

   CAC2_INJ_TIME  MG_INJ_TIME   DS_S  
0             10            4  0.009  
1             10            4  0.007  
2              9            4  0.013  
3              9            4  0.010  
4             10            5  0.013  
5              9            4  0.010  
6             10            5  0.009  
7              9            5  0.012  
8             11            7  0.004  
9              9            5  0.007

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6697 entries, 0 to 6696
Data columns (total 14 columns):
CASTNO           6697 non-null object
HM_WT            6697 non-null int64
AIM_S            6697 non-null float64
HM_S             6697 non-null float64
HM_C             6697 non-null float64
HM_SI            6697 non-null float64
HM_TI            6697 non-null float64
HM_MN            6697 non-null float64
CAC2             6697 non-null int64
MG               6697 non-null int64
HM_TEMP          6094 non-null float64
CAC2_INJ_TIME    6697 non-null int64
MG_INJ_TIME      6697 non-null int64
DS_S             6697 non-null float64
dtypes: float64(8), int64(5), object(1)
memory usage: 732.6+ KB


In [6]:
# Above we can see all columns have 6697 entries except HM_TEMP
# HM_TEMP has only 6097 entries.
# To Fill missing values I have taken mean of HM_TEMP values and fitted the resulting mean into missing positions.

In [7]:
data_fit=data.fillna(data["HM_TEMP"].mean())

In [8]:
data_fit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6697 entries, 0 to 6696
Data columns (total 14 columns):
CASTNO           6697 non-null object
HM_WT            6697 non-null int64
AIM_S            6697 non-null float64
HM_S             6697 non-null float64
HM_C             6697 non-null float64
HM_SI            6697 non-null float64
HM_TI            6697 non-null float64
HM_MN            6697 non-null float64
CAC2             6697 non-null int64
MG               6697 non-null int64
HM_TEMP          6697 non-null float64
CAC2_INJ_TIME    6697 non-null int64
MG_INJ_TIME      6697 non-null int64
DS_S             6697 non-null float64
dtypes: float64(8), int64(5), object(1)
memory usage: 732.6+ KB


In [9]:
data_fit.head(10)

CASTNO  HM_WT  AIM_S   HM_S   HM_C  HM_SI  HM_TI  HM_MN  CAC2  MG  HM_TEMP  \
0  V99790    171  0.005  0.040  4.572  0.518  0.069  0.040   347  49   1387.0   
1  V99791    161  0.005  0.035  4.580  0.559  0.070  0.041   361  45   1386.0   
2  V99789    170  0.005  0.042  4.590  0.468  0.044  0.036   355  52   1368.0   
3  V99787    159  0.005  0.034  4.530  0.737  0.077  0.040   313  44   1401.0   
4  V99782    162  0.005  0.042  4.560  0.443  0.056  0.037   360  55   1346.0   
5  V99781    165  0.005  0.035  4.520  0.480  0.056  0.037   323  49   1407.0   
6  V99779    167  0.005  0.040  4.560  0.630  0.069  0.037   349  51   1395.0   
7  V99778    163  0.005  0.040  4.560  0.547  0.057  0.036   346  78   1373.0   
8  V99777    164  0.005  0.050  4.500  0.397  0.049  0.037   373  72   1386.0   
9  V99776    162  0.005  0.039  4.520  0.622  0.069  0.040   344  56   1357.0   

   CAC2_INJ_TIME  MG_INJ_TIME   DS_S  
0             10            4  0.009  
1             10            4  0.007  
2              9            4  0.013  
3              9            4  0.010  
4             10            5  0.013  
5              9            4  0.010  
6             10            5  0.009  
7              9            5  0.012  
8             11            7  0.004  
9              9            5  0.007

In [10]:
type(data_fit)

pandas.core.frame.DataFrame

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [52]:
X=data_fit.iloc[:,1:13].values
Y=data_fit.iloc[:,13].values

In [53]:
print(X)

[[1.710e+02 5.000e-03 4.000e-02 ... 1.387e+03 1.000e+01 4.000e+00]
 [1.610e+02 5.000e-03 3.500e-02 ... 1.386e+03 1.000e+01 4.000e+00]
 [1.700e+02 5.000e-03 4.200e-02 ... 1.368e+03 9.000e+00 4.000e+00]
 ...
 [1.610e+02 5.000e-03 3.000e-02 ... 1.345e+03 9.000e+00 4.000e+00]
 [1.550e+02 5.000e-03 5.400e-02 ... 1.415e+03 1.100e+01 6.000e+00]
 [1.730e+02 5.000e-03 3.200e-02 ... 1.358e+03 8.000e+00 4.000e+00]]


In [54]:
print(Y)

[0.009 0.007 0.013 ... 0.004 0.008 0.005]


In [68]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=13)

In [69]:
print(X_train.shape)
print(X_test.shape)

(5357, 12)
(1340, 12)


In [70]:
lr=LinearRegression(normalize=True)
print(lr)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


In [71]:
lr.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [72]:
print(lr.intercept_)
print(lr.coef_)

-0.0049753060622914815
[ 1.78652931e-05  2.35794608e-01  1.42729331e-01  1.84366560e-03
  2.83989378e-03 -1.14286400e-01 -2.52265008e-02  6.42677411e-07
 -9.70815218e-05  6.94774194e-06 -5.14857398e-04  2.24877956e-04]


In [73]:
print(lr.score(X_train,Y_train))

0.3959911901664378


In [74]:
print(lr.score(X_test,Y_test))

0.37288269676090424


In [75]:
from sklearn.model_selection import cross_val_score

In [76]:
scores=cross_val_score(lr,X_train,Y_train,cv=10,scoring='r2')

In [77]:
print(scores)

[0.33945454 0.3513734  0.33776573 0.41367173 0.3926004  0.40709098
 0.37618944 0.40294373 0.41418107 0.45038874]


In [78]:
Y_predict=lr.predict(X_test)

In [79]:
# Calculating Accuracy
score=0
temp=0
for i in range(temp1):
    temp=Y_test[i]-Y_predict[i]
    if(temp>-0.003 and temp<0.003):
        score=score+1
score=score/(temp1)
print(score)
    

0.8761194029850746


In [67]:
temp1=Y_test.shape[0]
print(temp1)


1340


In [86]:
P_train,P_test,Q_train,Q_test=train_test_split(P,Q,test_size=0.2,random_state=5)

In [87]:
lin_model=LinearRegression()
lin_model.fit(P_train,Q_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [88]:
print(lin_model.score(P_train,Q_train))

0.26964510911151574


In [89]:
print(lin_model.score(P_test,Q_test))

0.293069422418734


In [90]:
columns_to_drop=["HM_TI","HM_MN","CASTNO","DS_S"]
X=data_fit.drop(columns_to_drop,axis=1)

In [91]:
print(X.shape)

(6697, 10)


In [92]:
X.head()

HM_WT  AIM_S   HM_S   HM_C  HM_SI  CAC2  MG  HM_TEMP  CAC2_INJ_TIME  \
0    171  0.005  0.040  4.572  0.518   347  49   1387.0             10   
1    161  0.005  0.035  4.580  0.559   361  45   1386.0             10   
2    170  0.005  0.042  4.590  0.468   355  52   1368.0              9   
3    159  0.005  0.034  4.530  0.737   313  44   1401.0              9   
4    162  0.005  0.042  4.560  0.443   360  55   1346.0             10   

   MG_INJ_TIME  
0            4  
1            4  
2            4  
3            4  
4            5

In [93]:
X=X.values

In [102]:
Q_predict=lin_model.predict(P_test)

In [103]:
print(Q_predict)

[0.00740143 0.01001698 0.00809541 ... 0.00712594 0.00869063 0.00588809]


In [105]:
Q_test.head()

5072    0.008
2509    0.010
6521    0.009
2956    0.010
4548    0.007
Name: DS_S, dtype: float64

In [107]:
print(Q_predict.shape)
print(Q_test.shape)

(1340,)
(1340,)


In [108]:
temp1=Q_test.shape[0]

In [109]:
print(temp1)

1340


In [113]:
Q_test=Q_test.values
Q_predict=Q_predict.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [114]:
# Calculating Accuracy
score=0
temp=0
for i in range(temp1):
    temp=Q_test[i]-Q_predict[i]
    if(temp>-0.003 and temp<0.003):
        score=score+1
score=score/(temp1)
print(score)
    

0.8395522388059702
